"""optimize_indexes

Revision ID: c690e57a78f0
Revises: a663512f71ca
Create Date: 2025-12-27 10:39:01.176826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c690e57a78f0"
down_revision: Union[str, Sequence[str], None] = "a663512f71ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # SAFE DROP: Use raw SQL to avoid errors if indexes don't exist
    # This handles cases where production DB has different/missing manual indexes
    indexes_to_drop = [
        "idx_chatbot_messages_at",
        "idx_chatbot_messages_created",
        "ix_chatbot_messages_created",
        "idx_chatbot_messages_session_id",
        "idx_chatbot_messages_session_created",
        "ix_chatbot_messages_created_at",
        "ix_chatbot_messages_id",
        "ix_chatbot_messages_message_type",
        "ix_chatbot_messages_session_id",
        "idx_chatbot_sessions_active",
        "idx_chatbot_sessions_last_accessed",
        "idx_chatbot_sessions_user_id",
        "ix_chatbot_sessions_is_active",
        "ix_chatbot_sessions_last_accessed_at",
        "ix_chatbot_sessions_session_id",
        "ix_chatbot_sessions_user_id",
        "idx_document_records_document_id",
        "idx_document_records_filename",
        "idx_document_records_knowledge_id",
        "ix_document_records_document_id",
        "ix_document_records_filename",
        "ix_document_records_knowledge_id",
    ]

    for index in indexes_to_drop:
        op.execute(f"DROP INDEX IF EXISTS {index}")

    op.create_index(
        "idx_messages_session_created",
        "chatbot_messages",
        ["session_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_sessions_active_last_accessed",
        "chatbot_sessions",
        ["is_active", "last_accessed_at"],
        unique=False,
    )
    op.create_index(
        "idx_sessions_user_last_accessed",
        "chatbot_sessions",
        ["user_id", sa.literal_column("last_accessed_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_document_records_knowledge_id",
        "document_records",
        ["knowledge_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Re-create the indexes that were dropped

    op.create_index(
        op.f("ix_document_records_knowledge_id"),
        "document_records",
        ["knowledge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_records_filename"),
        "document_records",
        ["filename"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_records_document_id"),
        "document_records",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_document_records_filename"),
        "document_records",
        ["filename"],
        unique=False,
    )
    op.create_index(
        op.f("idx_document_records_document_id"),
        "document_records",
        ["document_id"],
        unique=False,
    )
    op.drop_index("idx_sessions_user_last_accessed", table_name="chatbot_sessions")
    op.drop_index("idx_sessions_active_last_accessed", table_name="chatbot_sessions")
    op.create_index(
        op.f("ix_chatbot_sessions_user_id"),
        "chatbot_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_sessions_session_id"),
        "chatbot_sessions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_sessions_last_accessed_at"),
        "chatbot_sessions",
        ["last_accessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_sessions_is_active"),
        "chatbot_sessions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("idx_chatbot_sessions_user_id"),
        "chatbot_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_chatbot_sessions_last_accessed"),
        "chatbot_sessions",
        ["last_accessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_chatbot_sessions_active"),
        "chatbot_sessions",
        ["is_active"],
        unique=False,
        postgresql_where="(is_active = true)",
    )
    op.drop_index("idx_messages_session_created", table_name="chatbot_messages")
    op.create_index(
        op.f("ix_chatbot_messages_session_id"),
        "chatbot_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_messages_message_type"),
        "chatbot_messages",
        ["message_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_messages_id"), "chatbot_messages", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_chatbot_messages_created_at"),
        "chatbot_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_chatbot_messages_session_id"),
        "chatbot_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_chatbot_messages_created"),
        "chatbot_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_chatbot_messages_at"),
        "chatbot_messages",
        ["created_at"],
        unique=False,
    )

    # ### end Alembic commands ###
