"""create_chatbot_sessions

Revision ID: bd3dd440ae70
Revises:
Create Date: 2025-12-18 16:00:18.018956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd3dd440ae70"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatbot_sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "idx_chatbot_sessions_active",
        "chatbot_sessions",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        "idx_chatbot_sessions_last_accessed",
        "chatbot_sessions",
        ["last_accessed_at"],
        unique=False,
    )
    op.create_index(
        "idx_chatbot_sessions_user_id", "chatbot_sessions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_chatbot_sessions_is_active"),
        "chatbot_sessions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_sessions_last_accessed_at"),
        "chatbot_sessions",
        ["last_accessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_sessions_session_id"),
        "chatbot_sessions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_sessions_user_id"),
        "chatbot_sessions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chatbot_sessions_user_id"), table_name="chatbot_sessions")
    op.drop_index(op.f("ix_chatbot_sessions_session_id"), table_name="chatbot_sessions")
    op.drop_index(
        op.f("ix_chatbot_sessions_last_accessed_at"), table_name="chatbot_sessions"
    )
    op.drop_index(op.f("ix_chatbot_sessions_is_active"), table_name="chatbot_sessions")
    op.drop_index("idx_chatbot_sessions_user_id", table_name="chatbot_sessions")
    op.drop_index("idx_chatbot_sessions_last_accessed", table_name="chatbot_sessions")
    op.drop_index(
        "idx_chatbot_sessions_active",
        table_name="chatbot_sessions",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("chatbot_sessions")
    # ### end Alembic commands ###
