"""create_chatbot_messages

Revision ID: 79dcc04d4dae
Revises: bd3dd440ae70
Create Date: 2025-12-18 16:01:15.468820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79dcc04d4dae"
down_revision: Union[str, Sequence[str], None] = "bd3dd440ae70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatbot_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("message_type", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("reaction", sa.String(), nullable=True),
        sa.Column(
            "input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "message_type IN ('human', 'ai')", name="check_message_type"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chatbot_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chatbot_messages_at", "chatbot_messages", ["created_at"], unique=False
    )
    op.create_index(
        "idx_chatbot_messages_created",
        "chatbot_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_chatbot_messages_session_id",
        "chatbot_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_messages_created_at"),
        "chatbot_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_messages_id"), "chatbot_messages", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_chatbot_messages_message_type"),
        "chatbot_messages",
        ["message_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatbot_messages_session_id"),
        "chatbot_messages",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chatbot_messages_session_id"), table_name="chatbot_messages")
    op.drop_index(
        op.f("ix_chatbot_messages_message_type"), table_name="chatbot_messages"
    )
    op.drop_index(op.f("ix_chatbot_messages_id"), table_name="chatbot_messages")
    op.drop_index(op.f("ix_chatbot_messages_created_at"), table_name="chatbot_messages")
    op.drop_index("idx_chatbot_messages_session_id", table_name="chatbot_messages")
    op.drop_index("idx_chatbot_messages_created", table_name="chatbot_messages")
    op.drop_index("idx_chatbot_messages_at", table_name="chatbot_messages")
    op.drop_table("chatbot_messages")
    # ### end Alembic commands ###
