"""create_document_records

Revision ID: a663512f71ca
Revises: 79dcc04d4dae
Create Date: 2025-12-18 16:02:01.783235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a663512f71ca"
down_revision: Union[str, Sequence[str], None] = "79dcc04d4dae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_records",
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("knowledge_id", sa.Text(), nullable=False),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("filename", "knowledge_id", "document_id"),
    )
    op.create_index(
        "idx_document_records_document_id",
        "document_records",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "idx_document_records_filename", "document_records", ["filename"], unique=False
    )
    op.create_index(
        "idx_document_records_knowledge_id",
        "document_records",
        ["knowledge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_records_document_id"),
        "document_records",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_records_filename"),
        "document_records",
        ["filename"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_records_knowledge_id"),
        "document_records",
        ["knowledge_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_records_knowledge_id"), table_name="document_records"
    )
    op.drop_index(op.f("ix_document_records_filename"), table_name="document_records")
    op.drop_index(
        op.f("ix_document_records_document_id"), table_name="document_records"
    )
    op.drop_index("idx_document_records_knowledge_id", table_name="document_records")
    op.drop_index("idx_document_records_filename", table_name="document_records")
    op.drop_index("idx_document_records_document_id", table_name="document_records")
    op.drop_table("document_records")
    # ### end Alembic commands ###
