"""add_title_to_document_records

Revision ID: bc4d40571815
Revises: 5a5498a82777
Create Date: 2026-01-07 15:30:52.468741+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4d40571815'
down_revision: Union[str, Sequence[str], None] = '5a5498a82777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_records', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_records', 'title')
    # ### end Alembic commands ###
